-- Placeholder migration for PII data encryption
--
-- This migration file serves as a marker in the migration sequence but does not
-- perform any actual schema changes. The encryption of existing PII data must be
-- done using the application code via the standalone migration binary.
--
-- To migrate existing data, run:
--   cargo run --bin migrate_pii_encryption
--
-- The migration script will:
-- 1. Load all records with plaintext PII fields
-- 2. Encrypt using EncryptionService (AES-256-GCM)
-- 3. Generate blind indexes (HMAC-SHA256)
-- 4. Update *_encrypted and *_index columns
-- 5. Verify roundtrip decryption for data integrity
--
-- IMPORTANT: Take a database backup before running the migration script!
--
-- After successful data migration and a soak period, run the next migration
-- to drop the plaintext columns.

-- No-op: This migration intentionally does nothing
SELECT 1;
